/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Palette: #08090B · #47484D · #9B9C9E · #3B1A15 · #1A1D28
        // Primary accent derived from dark maroon #3B1A15 → ember red #E05A3A
        primary: "#E05A3A",
        "on-primary": "#1E0A05",
        "primary-container": "#3B1A15",
        "on-primary-container": "#FFCFBB",
        "primary-fixed": "#FFCFBB",
        "primary-fixed-dim": "#E05A3A",
        "on-primary-fixed": "#1E0A05",
        "on-primary-fixed-variant": "#B04228",
        secondary: "#9B9C9E",
        "on-secondary": "#1A1D28",
        "secondary-container": "#2E2B2A",
        "on-secondary-container": "#D4CFCA",
        "secondary-fixed": "#D4CFCA",
        "secondary-fixed-dim": "#9B9C9E",
        "on-secondary-fixed": "#0E0F11",
        "on-secondary-fixed-variant": "#47484D",
        tertiary: "#C4803A",
        "on-tertiary": "#1E0E00",
        "tertiary-container": "#3D2500",
        "on-tertiary-container": "#FFD9B0",
        "tertiary-fixed": "#FFD9B0",
        "tertiary-fixed-dim": "#C4803A",
        "on-tertiary-fixed": "#1E0E00",
        "on-tertiary-fixed-variant": "#7A4A18",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#08090B",
        "on-background": "#EDECEA",
        surface: "#08090B",
        "surface-dim": "#050608",
        "surface-bright": "#2C2D32",
        "surface-tint": "#E05A3A",
        "surface-variant": "#47484D",
        "surface-container-lowest": "#050608",
        "surface-container-low": "#111318",
        "surface-container": "#1A1D28",
        "surface-container-high": "#20232E",
        "surface-container-highest": "#282B36",
        "on-surface": "#EDECEA",
        "on-surface-variant": "#9B9C9E",
        outline: "#9B9C9E",
        "outline-variant": "#47484D",
        "inverse-surface": "#EDECEA",
        "inverse-on-surface": "#1A1D28",
        "inverse-primary": "#B04228",
        // Semantic aliases
        border: "#1A1D28",
        input: "#47484D",
        ring: "#E05A3A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "0.75rem",
      },
      fontFamily: {
        wordmark: ["Exo 2", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
